### ISSUE TITLE
⁭

### ISSUE THREAD

**Issue by andrea-berardi** [lucamorara/Vaccini#1]
⁭

**Comment by lucamorara** [comment]
Buonasera, non vedo come sia possibile che Lei sia riuscito a scaricare la mia applicazione visto che non è su alcuno Store Online.

Mi rivolgerò ai miei legali.

**Comment by andrea-berardi** [comment]
Ritengo a questo punto necessario chiederle di rinominare la repository in "Placebo", vista l'inutilità.


Buona serata.
